### ISSUE TITLE
Error while build logspout

### ISSUE THREAD

**Issue by Rohlik** [nathanleclaire/elk#1]
Hi,
I got this error:
`Step 8 : RUN go get && go build -ldflags "-X main.Version dev" -o /bin/logspout
 ---> Running in d096520678a8
package code.google.com/p/go.net/websocket: unable to detect version control system for code.google.com/ path
ERROR: Service 'logspout' failed to build: The command '/bin/sh -c go get && go build -ldflags "-X main.Version dev" -o /bin/logspout' returned a non-zero code: 1`

Can you help me?

**Comment by bjoeckel** [comment]
Hallo,
code.google is not accessible any more. I got it running like this: 
1. Find the line `code.google.com/p/go.net/websocket` in `./dockerfiles/logspout/httpstream/httpstream.go` 
2. substitute the line with `golang.org/x/net/websocket`
3. rebuild

Greetings, Ben
